name: PRWND
favicon: null
layout_spectrum: 0.98459
typography_spectrum: 0.5056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98afb5'
    - '#ffc18e'
    - '#792010'
    - '#855638'
    - '#ca875c'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
