name: PRWND
favicon: null
layout_spectrum: 0.5374252654146403
typography_spectrum: 0.2914692016784102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2a38f'
    - '#2b1d1a'
    - '#445046'
    - '#f0d6c7'
    - '#5c7673'
  brandStrength: 0.9642508961260319
  lightness: 0.796979001024738
  saturation: 0.23867500969208777
  rhythmicContrast: 0.3061003629118204
purpose: []
