name: PRWND
favicon: null
layout_spectrum: 0.98459
typography_spectrum: 0.14936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010609'
    - '#fefef9'
    - '#ffc644'
    - '#ff662d'
    - '#a3e4c8'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
