name: PRWND
favicon: null
layout_spectrum: 0.72537
typography_spectrum: 0.5056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2a38f'
    - '#2b1d1a'
    - '#445046'
    - '#f0d6c7'
    - '#5c7673'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
